image: Visual Studio 2017

branches:
  only:
  - master

skip_branch_with_pr: true
nuget:
  disable_publish_on_pr: true
  
skip_commits:
  files:
    - 'docs/**/*.*'  
    
init:
- ps: git config --global core.autocrlf true

build_script:
- ps: .\build\build.ps1

artifacts:
- path: .\build\nupkg\*.nupkg